# Generated by Django 4.1.7 on 2023-04-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_remove_utilisateur_nom_remove_utilisateur_prenom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='tuteur',
            new_name='idtuteur',
        ),
        migrations.RenameField(
            model_name='professeur',
            old_name='eleves',
            new_name='ideleves',
        ),
    ]
