# Generated by Django 4.1.7 on 2023-04-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_rename_tuteur_eleve_idtuteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='idtuteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.tuteur', verbose_name='tuteur'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='ideleves',
            field=models.ManyToManyField(through='comptes.Encadrement', to='comptes.eleve', verbose_name='eleves'),
        ),
    ]
