# Generated by Django 4.1.7 on 2023-04-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_alter_eleve_idtuteur_alter_professeur_ideleves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='classes_generales_enseignables',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='dernier_diplome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='filiere_dernier_diplome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='matieres_generales_enseignables',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
