# Generated by Django 4.1.7 on 2023-04-07 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_alter_professeur_classes_generales_enseignables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='idtuteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptes.tuteur', verbose_name='tuteur'),
        ),
    ]
