# Generated by Django 4.1.7 on 2023-04-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_alter_utilisateur_telephone1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone1',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone2',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
