# Generated by Django 4.1.7 on 2023-04-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_alter_utilisateur_telephone1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='matieres',
            field=models.CharField(default='', max_length=50),
        ),
    ]
