# Generated by Django 4.1.7 on 2023-04-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0010_eleve_jours_disponibles_eleve_periode_journee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='matieres',
        ),
        migrations.AlterField(
            model_name='eleve',
            name='jours_disponibles',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='periode_journee',
            field=models.CharField(max_length=50),
        ),
    ]
